[package]
name = "rust_kernel"
version = "0.1.0"
authors = ["Lukas Jorgensen <lukas.r.jorgensen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
